import {photo,photo1,photo3,photo4,photo5,photo6,photo7,photo8,photo9,    dress1img,
    dress1img1,
    dress1img2,dress1img3,dress1img4,dress1img5,dress2img,dress2img1,dress2img2,dress2img3,dress2img4,dress2img5,
     dress3img,dress3img1,dress3img2,dress3img3,dress3img4,dress4img1,dress4img2,dress4img3,dress4img4,dress5img,
    dress5img1,dress5img2,dress5img3,dress5img4,dress5img5,dress6img,dress6img1,dress6img2,dress6img3,dress7img,
     dress7img1,dress7img2,dress7img3,dress7img4,dress8img,dress8img1,dress8img2,dress8img3,dress9img,
    dress9img1,dress9img2,dress9img3,dress9img4,
    } from "../components/WomenComponents/assests"
export const WomenClothes=[
    {
        id:1,
        title:"Mango",
        desc:"Kimono & Caftan - Black - Regular fit",
        updatedprice:228,
        price:290,
        discount:10,
        fav:false,
        quantity:1,
        size:["XS","S","M","L","XL"],
        color:["#750430","#00A95D","#A2D2FC","#FF7A00"],
       addToCart:false,
       image: photo,
       img0:dress1img,
       img1:dress1img1,
       img2:dress1img2,
       img3:dress1img3,
       img4:dress1img4,
       img5:dress1img5
    },
    {
        id:2,
        title:"Zara",
        desc:"Midi top- Daily fit",
        updatedprice:95,
        price:145,
        discount:8,
        fav:false,
        quantity:1,
        size:["XS","S","M","L","XL"],
        color:["#750430","#00A95D","#A2D2FC","#FF7A00"],
        addToCart:false,
        image:photo1,
        img0:dress2img,
        img1:dress2img1,
        img2:dress2img2,
        img3:dress2img3,
        img4:dress2img4,
        img5:dress2img5


    },
    {
        id:3,
        title:"Mango dress",
        desc:"Kimono & Caftan - Colorful - Night club fit",
        updatedprice:365,
        price:487,
        discount:15,
        image:photo3,
        fav:false,
        quantity:1,
        size:["XS","S","M","L","XL"],
        color:["#750430","#00A95D","#A2D2FC","#FF7A00"],
        addToCart:false,
        img0:dress3img,
        img1:dress3img1,
        img2:dress3img2,
        img3:dress3img3,
        img4:dress3img4,
        img5:dress3img1

    },
    {
        id:4,
        title:"Uniqlo",
        desc:"Midi atlas Slim fit - bohemian",
        updatedprice:125,
        price:156,
        discount:8,
        image:photo4,
        fav:false,
        quantity:1,
        size:["XS","S","M","L","XL"],
        color:["#750430","#00A95D","#A2D2FC","#FF7A00"],
        addToCart:false,
        img0:photo4,
        img1:dress4img1,
        img2:dress4img2,
        img3:dress4img3,
        img4:dress4img4,
        img5:photo4

    },
    {
        id:5,
        title:"NBB",
        desc:"Bikini & seaside - Casual",
        updatedprice:300,
        price:365,
        discount:15,
        image:photo5,
        fav:false,
        quantity:1,
        size:["XS","S","M","L","XL"],
        color:["#750430","#00A95D","#A2D2FC","#FF7A00"],
        addToCart:false,
        img0:dress5img,
        img1:dress5img1,
        img2:dress5img2,
        img3:dress5img3,
        img4:dress5img4,
        img5:dress5img5
    },
    {
        id:6,
        title:"Rachel Pally",
        desc:"Dress - Beige - Shift - Casual",
        updatedprice:512,
        price:632,
        discount:20,
        image:photo6,
        fav:false,
        quantity:1,
        size:["XS","S","M","L","XL"],
        color:["#750430","#00A95D","#A2D2FC","#FF7A00"],
        addToCart:false,
        img0:dress6img,
        img1:dress6img1,
        img2:dress6img2,
        img3:dress6img3,
        img4:dress6img1,
        img5:photo6


    },
    {
        id:7,
        title:"Ralph lauren",
        desc:"Shirt-oversize - Minimalist",
        updatedprice:259,
        price:359,
        discount:11,
        image:photo7,
        fav:false,
        quantity:1,
        size:["XS","S","M","L","XL"],
        color:["#750430","#00A95D","#A2D2FC","#FF7A00"],
        addToCart:false,
        img0:dress7img,
        img1:dress7img1,
        img2:dress7img2,
        img3:dress7img3,
        img4:dress7img4,
        img5:photo7


    },
    {
        id:8,
        title:"Zara",
        desc:"Sweather - Black & White - Minimalist",
        updatedprice:420,
        price:428,
        discount:3,
        image:photo8,
        fav:false,
        quantity:1,
        size:["XS","S","M","L","XL"],
        color:["#750430","#00A95D","#A2D2FC","#FF7A00"],
        addToCart:false,
        img0:dress8img,
        img1:dress8img1,
        img2:dress8img2,
        img3:dress8img3,
        img4:dress8img1,
        img5:photo8


    },
    {
        id:9,
        title:"Uniqlo",
        desc:"Sweather - Casual",
        updatedprice:228,
        price:215,
        discount:10,
        image:photo9,
        fav:false,
        quantity:1,
        size:["XS","S","M","L","XL"],
        color:["#750430","#00A95D","#A2D2FC","#FF7A00"],
        addToCart:false,
        img0:dress9img,
        img1:dress9img1,
        img2:dress9img2,
        img3:dress9img3,
        img4:dress9img4,
        img5:photo9


    },
    
]