export {default as ComponentCategories} from '../common/ComponentCategories/ComponentCategories'
export {default as ComponentAd} from './HomePageComponents/ComponentAd/ComponentAd'
export {default as Trends} from './HomePageComponents/ComponentCard/SubComponent/Trends'
export {default as ComponentFlashSales} from "./HomePageComponents/ComponetFlashSales/ComponentFlashSales"
export {default as ComponentMustTrends} from "./HomePageComponents/ComponentMustTrends/ComponentMustTrends"
export {default as ComponentTopTrends} from './HomePageComponents/ComponentTopTrends/ComponentTopTrends'
export {default as ComponentBanner} from "./HomePageComponents/ComponentBanner/ComponentBanner"
export {default as ComponentBigTrends} from "./HomePageComponents/ComponentBigTrends/ComponentBigTrends"
export {default as ComponentBigSecTrends} from "./HomePageComponents/ComponentBigTrends/ComponentBigSecTrends"
export {default as DetailedBrandCoponent} from './DetailedBrandComponent/DetailedBrandComponent'
export {default as CheckoutComponent} from "./CheckoutComponent/CheckoutComponent"
export {default as ProductComponent} from "./ProductComponent/ProductComponent"